# Generated by Django 4.1.5 on 2023-01-14 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_slud_product_slug'),
    ]

    operations = [
        migrations.RunSQL("""
        insert into store_collection (title)
        values ('collection1')
        """, """
        delete from store_collection
        where title = 'collection1'
        """)
    ]
